/** Les icônes du DS (Material Design Icons et quelques Font Awesome, par la police Symbols Nerd Font). */
export const ICONS = [
  'account',
  'alert',
  'arrow_left',
  'arrow_up',
  'arrow_up_down',
  'bank',
  'calendar',
  'chart_donut',
  'chart_line',
  'check',
  'check_all',
  'checkbox_blank_outline',
  'checkbox_marked_outline',
  'chevron_down',
  'close',
  'cloud',
  'code_braces',
  'code_tags',
  'cog',
  'copyright',
  'crosshairs_gps',
  'delete',
  'eye',
  'eye_off',
  'fire',
  'filter_variant',
  'flag',
  'flag_checkered',
  'flash',
  'format_bold',
  'format_header_3',
  'format_italic',
  'format_list_bulleted',
  'format_list_numbered',
  'format_quote_close',
  'format_strikethrough_variant',
  'garage_open_variant',
  'gauge',
  'go_kart_track',
  'home',
  'leaf',
  'link_variant',
  'magnify',
  'map_marker',
  'map_marker_radius',
  'minus',
  'movie',
  'open_in_new',
  'pause',
  'play',
  'plus',
  'refresh',
  'sun_thermometer',
  'television',
  'tray_arrow_down',
  'tray_arrow_up',
  'view_dashboard',
  'volume_high',
  'volume_off',
  'water',
  'weather_cloudy',
  'weather_night',
  'weather_partly_cloudy',
  'weather_pouring',
  'weather_rainy',
  'weather_sunny',
  'weather_windy',
] as const

/** Les icônes Font Awesome de la même police (nf-fa-*), quand Material Design n'a pas la bonne. */
export const FA_ICONS = ['rocket', 'wind'] as const

export type IconName = (typeof ICONS)[number] | `fa-${(typeof FA_ICONS)[number]}`
