/** Les icônes du DS (Material Design Icons, par la police Symbols Nerd Font). */
export const ICONS = [
  'account',
  'alert',
  'arrow_left',
  'arrow_up',
  'arrow_up_down',
  'bank',
  'chart_donut',
  'chart_line',
  'check',
  'check_all',
  'chevron_down',
  'close',
  'cog',
  'copyright',
  'crosshairs_gps',
  'delete',
  'eye',
  'eye_off',
  'fire',
  'format_list_bulleted',
  'home',
  'leaf',
  'magnify',
  'movie',
  'open_in_new',
  'pause',
  'play',
  'plus',
  'refresh',
  'sun_thermometer',
  'television',
  'tray_arrow_down',
  'tray_arrow_up',
  'view_dashboard',
  'volume_high',
  'volume_off',
  'weather_night',
  'weather_sunny',
] as const

export type IconName = (typeof ICONS)[number]
